Feature/design system
xmartlabs/ftnt pull request #17
Opened 2022-10-28 19:24 UTC by SolMendiola

# :star: Feature

---

#### :pencil2: Description:

Added design system

---

#### :movie_camera: Screen record:

#### iOS

![Screen Shot 2022-10-28 at 16 22 23](https://user-images.githubusercontent.com/57235692/198716014-035070cf-1445-457d-9482-8b40aa8295a7.png)

![Simulator Screen Shot - iPhone 13 - 2022-10-28 at 16 23 48](https://user-images.githubusercontent.com/57235692/198716039-2277a2e8-b14d-4d28-8274-9e8d76750b65.png)

2022-10-28 20:05 UTC, mirland requested changes

2022-10-28 20:05 UTC, mirland commented on lib/ui/common/input_text.dart
> +            context.theme.textStyles.bodyLarge?.copyWith(color: Colors.black),
you cannot use a fixed color, it depends on the theme

2022-10-28 20:05 UTC, mirland commented on lib/ui/common/app_dialog.dart
> +              SizedBox(height: 20,),
```suggestion
              SizedBox(height: 20),
```

2022-10-28 20:05 UTC, mirland commented on lib/ui/theme/app_colors.dart
> +        }),
move to one variable?

2022-10-28 20:05 UTC, mirland commented on lib/ui/theme/app_colors.dart
> +        ),
same?

2022-10-28 20:05 UTC, mirland commented on lib/ui/tips/tips_screen.dart
> +                  title: 'titulo',
english?

2022-10-28 20:05 UTC, mirland commented on lib/ui/tips/tips_screen.dart
>  class _TipContentScreen extends StatelessWidget {
I would create a catalog screen

2022-10-31 16:20 UTC, mirland commented on lib/ui/catalog/catalogScreen.dart
> +import 'package:flutter/material.dart';
the file name is wrong

2022-10-31 16:20 UTC, mirland commented on lib/ui/catalog/catalogScreen.dart
> +                contentText: 'context',
```suggestion
                contentText: 'content',
```

2022-10-31 16:20 UTC, mirland commented on lib/ui/common/app_dialog.dart
> +    required this.negativeOption,
it shouldnt be required

2022-10-31 16:20 UTC, mirland commented on lib/ui/common/app_dialog.dart
> +  final String positiveOption;
shouldnt be option1 and option two?

2022-10-31 16:20 UTC, mirland commented on lib/ui/common/input_text.dart
> +    this.width,
Are you using it?

2022-10-31 16:20 UTC, mirland commented on lib/ui/common/input_text.dart
> +        onChanged: (_) {},
calback?

2022-10-31 16:20 UTC, mirland commented on lib/ui/common/search.dart
> +            // string
check it

2022-10-31 16:20 UTC, mirland commented on lib/ui/tips/tips_screen.dart
> -        );
rollback

2022-10-31 16:43 UTC, f7deleon requested changes

2022-10-31 16:43 UTC, f7deleon commented on lib/ui/common/app_dialog.dart
> +        ),
what happens if the content is greater than 400.w?

2022-10-31 16:43 UTC, f7deleon commented on lib/ui/common/app_dialog.dart
> +                negativeOption!,
i think that if you required this you should make it non nullable

2022-10-31 16:43 UTC, f7deleon commented on lib/ui/common/fab.dart
> +      onPressed: () {},
what happends if its pressed?

2022-10-31 16:43 UTC, f7deleon commented on lib/ui/common/search.dart
> +            textHint: 'Search',
localize this string

2022-10-31 16:43 UTC, f7deleon commented on lib/ui/common/search.dart
> +class Search extends StatelessWidget {
i think that search is maybe too general what about SearchBar or something like that?

2022-10-31 16:43 UTC, f7deleon commented on lib/ui/theme/app_colors.dart
> +        surface: generateMaterialColor(color: Color(0xffE0F4FF)),
this is ok?

2022-10-31 19:13 UTC, mirland commented on lib/ui/catalog/catalog_screen.dart
> +
Do you need it?
```suggestion
```

2022-10-31 19:13 UTC, mirland commented on lib/ui/common/app_dialog.dart
> +            if (optionTwo is String)
why? check if it not null

2022-10-31 19:13 UTC, mirland commented on lib/ui/common/fab.dart
> +      this.action})
comma

2022-10-31 19:13 UTC, mirland commented on lib/ui/common/input_text.dart
> +        onChanged: (word) => action!(word),
action could be null, fix it

2022-10-31 20:05 UTC, f7deleon approved these changes

2022-10-31 21:45 UTC, mirland approved these changes

2022-10-31 21:45 UTC, mirland commented on lib/l10n/intl_en.arb
>  }
```suggestion
}

```

2022-10-31 23:10 UTC, merged