Feature/count viewed
xmartlabs/ftnt pull request #28
Opened 2022-11-11 13:33 UTC by SolMendiola

<!---

# :star: Feature

---

#### :pencil2: Description:

Implemented sorting by amount of views and random number and save only one view per session

---

#### :movie_camera: Screen record:

#### iOS

![image](https://user-images.githubusercontent.com/57235692/201350911-d59afeba-a9e2-4d25-94bf-a2c8d3a490df.png)

2022-11-11 15:00 UTC, mirland requested changes

2022-11-11 15:40 UTC, f7deleon commented on lib/core/model/db/amount_views_db_entity.dart
> +  int amountViews;
this should be a foreign key also

2022-11-11 21:25 UTC, mirland commented on lib/core/model/db/tip_amount_views_db_entity.dart
> +  @primaryKey
maybe an space?

2022-11-11 21:25 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +  Set<String> tipsAlreadyVisited = {};
Don't mix injected variables with class variables

2022-11-11 21:25 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +          (event) => (event.isData)
use response instead of event

2022-11-11 21:25 UTC, mirland commented on lib/core/source/localSource/amount_views_local_source.dart
> +  Future<List<TipAmountViewsDbEntity>> getAmountsViewById(String id);
whay is returning a list? you should return only one

2022-11-11 21:25 UTC, mirland commented on lib/core/source/localSource/amount_views_local_source.dart
> +  )
```suggestion
  @Query('SELECT * FROM ${TipAmountViewsDbEntity.tableName} ORDER BY amountViews')
```

2022-11-11 21:25 UTC, mirland commented on lib/core/source/localSource/amount_views_local_source.dart
> +  Future<List<TipAmountViewsDbEntity>> getAmountsViewById(String id);
Just an idea: you can mabe return the amount (the int)

2022-11-11 21:25 UTC, mirland commented on lib/ui/tips/tips_cubit.dart
> +  late StreamSubscription<List<Tip>> suscriptionToTips;
typo

2022-11-11 21:25 UTC, mirland commented on lib/ui/tips/tips_cubit.dart
> +  void _suscribeToTips() {
typo

2022-11-11 21:25 UTC, mirland commented on lib/ui/tips/tips_cubit.dart
> +    _tipRepository.changeAmountsTip(tip);
unawaited?

2022-11-14 16:36 UTC, mirland approved these changes

2022-11-14 16:36 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +  Future<void> changeAmountsTip(Tip tip) async {
the name 🤔 
setTipAsViewedInSession? I don't know, just an idea

2022-11-14 16:55 UTC, merged