Added get data from GitHub
xmartlabs/ftnt pull request #7
Opened 2022-10-17 19:20 UTC by SolMendiola

# :star: Feature

---

#### :link: Notion:

- [Get data from GitHub](https://www.notion.so/xmartlabs/Get-data-from-GitHub-70f0ee056eb94c70b1d59064998add9a)

---

#### :pencil2: Description:

Added logic to get tips from GitHub

---

#### :movie_camera: Screen record:

#### iOS

<img width="1561" alt="Screen Shot 2022-10-17 at 16 13 41" src="https://user-images.githubusercontent.com/57235692/196262788-67aa1d37-3998-4a48-b7ba-638a5131b8a0.png">

---

#### :pushpin: Notes:

- The idea is to show this data in nexts cards. 

---

2022-10-17 21:57 UTC, f7deleon commented on lib/core/model/tip.dart
> +      required String path}) = _Tip;
add trailing comma and indent

2022-10-17 22:48 UTC, mirland requested changes

2022-10-17 22:48 UTC, mirland commented on lib/core/di/di_repository_module.dart
> +import '../source/tip_remote_source.dart';
avoid relative path imports

2022-10-17 22:48 UTC, mirland commented on lib/core/di/di_repository_module.dart
> +    registerLazySingleton(() => TipRemoteSource(get()));
Indent alpha

2022-10-17 22:48 UTC, mirland commented on lib/core/model/serializer/tip_serializer.dart
> +}
NL

2022-10-17 22:48 UTC, mirland commented on lib/core/model/serializer/tip_serializer.dart
> +import '../tip.dart';
same

2022-10-17 22:48 UTC, mirland commented on lib/core/model/tip.dart
> +      required String path}) = _Tip;
use a tailing comma and indent

2022-10-17 22:48 UTC, mirland commented on lib/core/model/tip.dart
> +  factory Tip(
Don't we need more info? For example the code file

2022-10-17 22:48 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +import '../source/tip_remote_source.dart';
check it

2022-10-17 22:48 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +  Future<List<Tip>?> getTips() async => (await _tipRemoteSource.getTips())
avoid nullable list

2022-10-17 22:48 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +  Future<List<Tip>?> getTips() async => (await _tipRemoteSource.getTips())
Remove the `async` and the `await`.
You are creating a future to just await another future

2022-10-17 22:48 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +      RegExp(r'[^\s]+(\.(jpe?g|png|gif|bmp))$', caseSensitive: false);
Shouldnt be done in the remote source. It's too specific

2022-10-17 22:48 UTC, mirland commented on lib/core/model/tips_response.dart
> +      {required List<Tip> tree}) = _TipResponse;
Is it ok? Shouldnt be a list of file metadata?

2022-10-17 22:48 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +  Future<TipResponse> getTips() async => (await _httpService
remove async and await

2022-10-17 22:48 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +  static const _urlGetTips = '/git/trees/main?recursive=All';
it's not the list of tips, it's the list of files

2022-10-17 22:48 UTC, mirland commented on lib/ui/signin/signin_screen.dart
> +import '../../core/repository/tip_repository.dart';
check it

2022-10-17 22:48 UTC, mirland commented on lib/ui/signin/signin_screen.dart
> +  final TipRepository _tipRepository = DiProvider.get();
you shouldn't inject a repository in the view. You should do that only in the cubit

2022-10-17 22:48 UTC, mirland commented on lib/ui/welcome/welcome_cubit.dart
> +import '../../core/repository/tip_repository.dart';
check it, (in all files)

2022-10-17 22:48 UTC, mirland commented on lib/ui/welcome/welcome_cubit.dart
> +
?

2022-10-17 22:48 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +import '../model/tip.dart';
cjheck it

2022-10-17 22:48 UTC, mirland commented on lib/core/model/tips_response.dart
> +      {required List<Tip> tree}) = _TipResponse;
let discuss it, but I'd not use a list of tips here

2022-10-17 22:48 UTC, mirland commented on assets/environments/.env
>  SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dG1nc25rYXhncmpnY2tkbW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjE4OTkyMTMsImV4cCI6MTk3NzQ3NTIxM30.yEGUwgmvdP9bDeSyh
rm

2022-10-17 22:48 UTC, mirland commented on lib/core/model/serializer/tip_serializer.dart
> +class TipStockTypeMapper extends StockTypeMapper<ProjectDbEntity, Tip>{
you are not using it

2022-10-17 22:48 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +  Future<List<Tip>?> getTips() async => (await _tipRemoteSource.getTips())
I'd use a stream instead of a future

2022-10-17 22:48 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +      serializer:  (tip) => TipResponse.fromJson(tip)))
check the indentation

2022-10-19 13:04 UTC, mirland commented on lib/core/model/github_file_response.dart
> +}
```suggestion
}

```

2022-10-19 13:04 UTC, mirland commented on lib/core/model/serializer/tip_serializer.dart
> +class TipStockTypeMapper extends StockTypeMapper<ProjectDbEntity, Tip> {
rm (you are not using it)

2022-10-19 13:04 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +  Future<List<Tip>?> getTips() async =>
Change to a stream or add a todo

2022-10-19 13:04 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +      "https://github.com/vandadnp/flutter-tips-and-tricks/blob/main/";
add it in the config file

2022-10-19 13:04 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +  static const _nameMainFolder = "tipsandtricks/";
same

2022-10-19 13:04 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +  }
just inline?

2022-10-19 13:04 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +    final List<Tip> listTips = [];
avoid it, it's better if you use functional oparators to transform the collection

2022-10-19 13:04 UTC, mirland commented on pubspec.yaml
> +  dartx: ^1.1.0
alpha and remove ^

2022-10-19 13:04 UTC, mirland commented on lib/ui/signin/signin_screen.dart
> +  final TipRepository _tipRepository = DiProvider.get();
check it

2022-10-19 14:47 UTC, f7deleon commented on lib/core/repository/tip_repository.dart
> +  Future<List<Tip>?> getTips() async =>
Also it shouldn't be nullable in the worst case it should return the empty list

2022-10-19 14:47 UTC, f7deleon commented on lib/core/source/tip_remote_source.dart
> +            serializer: (tip) => GitHiubTreeResponse.fromJson(tip)))
this is not a tip anymore

2022-10-19 14:47 UTC, f7deleon commented on lib/core/source/tip_remote_source.dart
> +    return _createTip(response);
i think that either you use all `then()` and made it a single line function or use await and do the 
```
value.tree
            .where((element) => element.path.contains(_nameMainFolder))
            .groupBy((element) => element.path.split('/').second)
```
outside of the Future since now its kind of a hybrid between the two

2022-10-19 14:47 UTC, f7deleon commented on lib/core/source/tip_remote_source.dart
> +  List<Tip> _createTip(Map<String, List<GitHubFile>> gitResponse) {
maybe `_mapToTips` instead of `_createTip`? since you are not creating but mapping one model to another
```suggestion
  List<Tip> _mapToTips(Map<String, List<GitHubFile>> gitResponse) {
```

2022-10-19 14:47 UTC, f7deleon commented on lib/core/source/tip_remote_source.dart
> +      listTips.add(Tip(
you cannot use an `add` inside a `map` since its against the map purpose

2022-10-19 14:48 UTC, f7deleon commented on lib/ui/welcome/welcome_cubit.dart
> +  final TipRepository _tipRepository = DiProvider.get();
check it

2022-10-19 20:45 UTC, mirland commented on assets/environments/.env
> +NAME_MAIN_FOLDER=tipsandtricks/
I would not add them here, because it's a static value. I'd use just a constant in the config file @f7deleon @sante what do you think?

2022-10-19 20:45 UTC, mirland commented on lib/core/model/tip.dart
> +    required String? imageUrl,
shouldnt be null, the tip will not makes sense if we have not image

2022-10-19 20:45 UTC, mirland commented on lib/core/source/tip_remote_source.dart
>    static const _prefix =
use the constant from the config file

2022-10-19 20:45 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +              serializer: (file) => GitHubTreeResponse.fromJson(file)))
cannot use just the reference?
```suggestion
              serializer: GitHubTreeResponse.fromJson))
```

2022-10-19 20:45 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +            .associateBy((file) => FileType.fromPath(file.path));
same, cannot use the reference?
```suggestion
            .associateBy(FileType.fromPath);
```

2022-10-19 20:45 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +              : null,
I would not use tips without images

2022-10-19 20:45 UTC, mirland commented on lib/ui/signin/signin_cubit.dart
> +  }
todo or something like that

2022-10-19 20:45 UTC, mirland commented on lib/ui/signin/signin_screen.dart
> +                  .isNotEmpty)
sl?

2022-10-19 20:45 UTC, mirland commented on pubspec.yaml
> +  dartx: 1.1.0
sort alpha

2022-10-19 20:45 UTC, mirland commented on lib/ui/signin/signin_screen.dart
> +                  onPressed: cubit.signIn,
I would not change this widget

2022-10-19 20:45 UTC, mirland commented on lib/ui/signin/signin_cubit.dart
> +    return _tipRepository.getTips();
I'd not change the sign in cubit, I don't know what do you think

2022-10-19 20:47 UTC, mirland commented on assets/environments/.env
> +URL_GET_TIPS=/git/trees/main?recursive=All
I would add it in the remote source, I would not add it here (we cannot define all endpoints here)

2022-10-20 18:22 UTC, mirland approved these changes

2022-10-20 18:22 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +  List<Tip> _mapToTips(Map<String, List<GitHubFile>> gitResponse) =>
I'm not sure if I'd use the list, I'd process each entry. Furthermore, I would rename the method to `_createTip` or something like that

2022-10-20 18:22 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +          name: tipDir.path.split('/').second,
shouldn't you ad spaces?

2022-10-20 18:22 UTC, mirland commented on lib/ui/signin/signin_cubit.dart
> +    _tipRepository.getTips();
```suggestion
```
If you want yo can keep it but you have to add a todo comment to remove it

2022-10-20 20:10 UTC, mirland approved these changes

2022-10-20 20:10 UTC, mirland commented on lib/core/source/tip_remote_source.dart
> +      mdUrl: Config.prefixUrl + (files[FileType.md]?.path ?? ''),
I would prefer null than empty, but we can change it later

2022-10-20 20:18 UTC, f7deleon approved these changes
Nice! 🎉

2022-10-21 00:53 UTC, merged